### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by BishwajithBN** [urbanairship/android-library#102]
### Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.util.ArrayMap.get(java.lang.Object)' on a null object reference
       at android.os.BaseBundle.getString(BaseBundle.java:921)
       at com.urbanairship.job.JobInfo.fromPersistableBundle(JobInfo.java:268)
       at com.urbanairship.job.AndroidJobService.onStartJob(AndroidJobService.java:21)
       at android.app.job.JobService$JobHandler.handleMessage(JobService.java:126)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5527)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)

**Comment by crow** [comment]
@BishwajithBN The team will look into it, thanks for reporting this.

**Comment by marc-scig** [comment]
@BishwajithBN as with the other issue you filed, please provide some additional information so we can narrow our search. OS version, UA SDK version and any relevant surrounding logs aside from the stacktrace itself. We may have fixed particular issue as of SDK 9.5.5.

**Comment by BishwajithBN** [comment]
@**marc-scig** : Please use this [fabric link](http://crashes.to/s/1ef00b54a90) to find more information

**Comment by BrianBatchelder** [comment]
@BishwajithBN : Please provide your Urban Airship dependencies and their versions. In the future, please follow the issue template when submitting an issue, as the information you provide is very helpful for our analysis.

**Comment by BrianBatchelder** [comment]
As @marc-scig wrote above, we believe this issue was fixed in SDK 9.5.5. Please update your SDK.
