### ISSUE TITLE
java.lang.OutOfMemoryError:

### ISSUE THREAD

**Issue by BishwajithBN** [urbanairship/android-library#103]
# Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 7452389580 byte allocation with 2097152 free bytes and 179MB until OOM
       at android.util.ArrayMap.allocArrays(ArrayMap.java:198)
       at android.util.ArrayMap.(ArrayMap.java:252)
       at android.os.BaseBundle.unparcel(BaseBundle.java:216)
       at android.os.BaseBundle.getString(BaseBundle.java:927)
       at com.urbanairship.job.JobInfo.fromPersistableBundle(JobInfo.java:268)
       at com.urbanairship.job.AndroidJobService.onStartJob(AndroidJobService.java:21)
       at android.app.job.JobService$JobHandler.handleMessage(JobService.java:126)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:150)
       at android.app.ActivityThread.main(ActivityThread.java:5643)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:799)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:689)

**Comment by marc-scig** [comment]
Hi @BishwajithBN, 

Thanks for bringing this to our attention, we'll look into it as soon as we can. Something that would be helpful would be more context surrounding your app and this issue so that we can figure out what was going on at the time. In particular, the version of the SDK that you're using, OS version, and surrounding output from logcat. We fixed some issues with PersistableBundle in SDK version 9.5.5, and the current version is 9.6.0.

**Comment by BishwajithBN** [comment]
Hi @**marc-scig**,

We are not sure about the scenario as we found this crash information in fabric. But this crash has happened only in Android 6.0 and 6.0.1.
As our current version is 9.3.1, we will upgrade it to the latest version and report you back if same crash is happening.
So I will be closing this issue for now.

Thanks,
Bishwajith
