### ISSUE TITLE
Getting Crash on some devices

### ISSUE THREAD

**Issue by kumaratulismu** [urbanairship/android-library#104]
We are getting crashes on devices, mostly on kitkat. Urban Sdk version :9.0.1

Ref:http://crashes.to/s/97554f56ce1

Crash log:

Fatal Exception: java.lang.RuntimeException: bad array lengths
       at android.os.Parcel.readIntArray(Parcel.java:789)
       at android.app.INotificationManager$Stub$Proxy.enqueueNotificationWithTag(INotificationManager.java:247)
       at android.app.NotificationManager.notify(NotificationManager.java:135)
       at android.support.v4.app.NotificationManagerCompat.notify(NotificationManagerCompat.java:210)
       at com.urbanairship.push.IncomingPushRunnable.displayNotification(IncomingPushRunnable.java:304)
       at com.urbanairship.push.IncomingPushRunnable.processPush(IncomingPushRunnable.java:169)
       at com.urbanairship.push.IncomingPushRunnable.run(IncomingPushRunnable.java:81)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at java.lang.Thread.run(Thread.java:856)

------------------------------------------------------------
Still getting crash after updating SDK to v9.3.1
http://crashes.to/s/58fd57553ec

Please confirm whether this is fixed in latest release?

**Comment by BrianBatchelder** [comment]
@kumaratulismu : Thanks for reporting this. We will look into it.

**Comment by kumaratulismu** [comment]
@rlepinski Thanks for your revert.

Please find android configurations.
CompileSdkVersion = 28
BuildToolsVersion = '28.0.3'
MinSdkVersion = 16  
TargetSdkVersion = 28
SupportLibraryVersion = '27.1.1'

Yes, we are using notification factory. Attaching the files for reference.

[Archive.zip](https://github.com/urbanairship/android-library/files/2744853/Archive.zip)

However, we are not able to reproduce the exact payload which could be causing the crash.

Yeah! it could be a framework issue.Coming on other notification engines also

Ref- https://github.com/OneSignal/OneSignal-Android-SDK/issues/394

Not sure what to do, its crashing for a lot of users.

**Comment by rlepinski** [comment]
@kumaratulismu Today we will release a patch to catch those exceptions. Your end users will have their notifications dropped, so we will still need to figure out a solution and if we just catch the exception it will be hard for you to know when its fixed. Next week we will try to release a minor update that allows you to intercept that error and upload it somewhere so you can track it.

Ill take a look at your factory soon to see if anything stands out.

**Comment by rlepinski** [comment]
@kumaratulismu Release 9.6.1 is going out. Please update it to prevent the crash. Working on 9.7.0 so you can still gather info when a notification fails to post.
