### ISSUE TITLE
Fatal Exception: java.lang.OutOfMemoryError Issues after UA Lib Upgrade

### ISSUE THREAD

**Issue by wezley98** [urbanairship/android-library#106]
# Preliminary Info

### What Urban Airship dependencies are you using?
 implementation "com.urbanairship.android:urbanairship-sdk:9.5.2"

### What are the versions of any relevant development tools you are using?
  playServices = '15.0.1'

We are using GCM.

# Report

### What unexpected behavior are you seeing?
Crashes reported in fabric. 1000+ in last 30 days.

<img width="757" alt="screenshot 2019-01-07 at 14 59 49" src="https://user-images.githubusercontent.com/1488209/50775036-04b26680-128d-11e9-8151-d1c53cf2e062.png">

### What is the expected behavior?
No Crashes

### What are the steps to reproduce the unexpected behavior?
Unknown, We started seeing crashes after upgrading from v8.9.6 - v9.5.2 of the UA SDK

### Do you have logging for the issue?
```
Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 48 byte allocation with 0 free bytes and 3GB until OOM
       at android.app.Notification$BuilderRemoteViews.clone(Notification.java:4968)
       at android.app.Notification$BuilderRemoteViews.clone(Notification.java:4954)
       at android.app.Notification.cloneInto(Notification.java:1471)
       at android.app.Notification.clone(Notification.java:1383)
       at android.app.NotificationManager.notify(NotificationManager.java:149)
       at android.support.v4.app.NotificationManagerCompat.notify(SourceFile:212)
       at com.urbanairship.push.IncomingPushRunnable.postNotification(SourceFile:256)
       at com.urbanairship.push.IncomingPushRunnable.postProcessPush(SourceFile:194)
       at com.urbanairship.push.IncomingPushRunnable.processPush(SourceFile:149)
       at com.urbanairship.push.IncomingPushRunnable.run(SourceFile:92)
       at com.urbanairship.push.PushService$1.run(SourceFile:56)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
```

Another one:

```
Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 2073612 byte allocation with 843542 free bytes and 823KB until OOM
       at dalvik.system.VMRuntime.newNonMovableArray(VMRuntime.java)
       at android.graphics.Bitmap.nativeCreate(Bitmap.java)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:939)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:912)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:843)
       at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:719)
       at android.support.v4.app.NotificationCompat$Builder.reduceLargeIconSize(SourceFile:1002)
       at android.support.v4.app.NotificationCompat$Builder.setLargeIcon(SourceFile:977)
       at com.urbanairship.push.notifications.StyleNotificationExtender.applyBigPictureStyle(SourceFile:194)
       at com.urbanairship.push.notifications.StyleNotificationExtender.applyStyle(SourceFile:120)
       at com.urbanairship.push.notifications.StyleNotificationExtender.extend(SourceFile:81)
       at android.support.v4.app.NotificationCompat$Builder.extend(SourceFile:1568)
       at com.urbanairship.push.notifications.NotificationFactory.createNotificationBuilder(SourceFile:490)
       at com.urbanairship.push.notifications.DefaultNotificationFactory.createNotification(SourceFile:59)
       at com.urbanairship.push.notifications.NotificationFactory.createNotificationResult(SourceFile:395)
       at com.urbanairship.push.notifications.NotificationFactory.createNotificationResult(SourceFile:426)
       at com.urbanairship.push.IncomingPushRunnable.postProcessPush(SourceFile:184)
       at com.urbanairship.push.IncomingPushRunnable.processPush(SourceFile:149)
       at com.urbanairship.push.IncomingPushRunnable.run(SourceFile:92)
       at com.urbanairship.push.PushService$1.run(SourceFile:56)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by rlepinski** [comment]
@wezley98 Are you using a custom notification factory? Looks like you are using big pictures, do you have a sample push payload you can provide?

**Comment by wezley98** [comment]
@rlepinski The issues only started to occur after we upgraded the UrbanAirship SDK. v8.9.6 - v9.5.2

<img width="1135" alt="screenshot 2019-01-08 at 11 30 13" src="https://user-images.githubusercontent.com/1488209/50828271-cd00f880-1338-11e9-9672-01798a3b9afa.png">

**Comment by rlepinski** [comment]
@wezley98 Did you also make other changes to the app not just the UA SDK? When you pulled in the newer SDK it also pulled in newer versions of the support library and play services.

Its possible the new version of the SDK has a slightly higher memory footprint then the old version and thats why you are now seeing this issue. Any chance you can profile your application to see whats using all the memory? I will check our internal sample apps to make sure this is no memory leaks or anything using an absurd amount of memory, but we really need it done with the app experiencing the issue. Where an OutOfMemoryError is thrown does not necessary point to the place with an issue. In this case, a notification requires a few temporary bitmaps to build the notification, so it uses a bit of memory to do so. It just so happens the app is out of memory at this time so it looks to be UA that is causing the issue, but really it could be something else going on.

**Comment by rlepinski** [comment]
Closing for now. Ill reopen if you have more info points to as the memory hog/leak.
