### ISSUE TITLE
android.database.CursorWindowAllocationException: Cursor window allocation of 2097152 bytes failed

### ISSUE THREAD

**Issue by gaurav-mishra8** [urbanairship/android-library#113]
### What Urban Airship dependencies are you using?
ℹcom.urbanairship.android:urbanairship-sdk:9.5.2

### What are the versions of any relevant development tools you are using?
ℹ Android Studio - 3.3
Gradle version - 3.3.0
Google Support lib version - 27.1.1

# Report

### What unexpected behavior are you seeing?
ℹ App crashing due to Cursor Window allocation Exception

### What is the expected behavior?
ℹ App should not crash

### What are the steps to reproduce the unexpected behavior?
ℹ Normally run app on Android Pie (Samsung S9 Pie)

### Do you have logging for the issue?
ℹ Fatal Exception: android.database.CursorWindowAllocationException: Cursor window allocation of 2097152 bytes failed. 
       at android.database.CursorWindow.(CursorWindow.java:136)
       at android.database.CursorWindow.(CursorWindow.java:114)
       at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:198)
       at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:143)
       at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:137)
       at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:220)
       at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:259)
       at com.urbanairship.automation.AutomationDataManager.generateSchedules(SourceFile:710)
       at com.urbanairship.automation.AutomationDataManager.getScheduleEntries(SourceFile:599)
       at com.urbanairship.automation.AutomationEngine$22.run(SourceFile:979)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:193)
       at android.os.HandlerThread.run(HandlerThread.java:65)

Are you closing all the cursors properly?

**Comment by marc-scig** [comment]
Hi @gaurav-mishra8,

Thanks for the report, we'll look into it. We did some work several versions ago to fix some issues with cursors in in-app automation, but it's possible there might still be some problems. Latest SDK version is 9.7, but I don't believe much has changed as far as that's concerned since 9.5.2.

**Comment by rlepinski** [comment]
@gaurav-mishra8 Yes we close our cursors. You can enable strict mode to see if another library might be the problem. This might not be related to cursors but instead could be an OOM error thats failing on the cursor allocation.

Do you have any stats on # of crashes or what devices are affected? Is it reproducible?

**Comment by gaurav-mishra8** [comment]
@rlepinski I did strict mode checking but couldn't find leak specifically related to urban airship, will monitor it more with respect to overall app memory usage.
Thanks.
