### ISSUE TITLE
Couldn't convert result of type java.lang.Boolean to java.lang.String

### ISSUE THREAD

**Issue by rafagcamargo** [urbanairship/android-library#115]
### What Urban Airship dependencies are you using?
`com.urbanairship.android:urbanairship-fcm:9.7.0`

### What are the versions of any relevant development tools you are using?

- Android API Level 23
- AndroidX Components

# Report

### What unexpected behavior are you seeing?
`java.lang.ClassCastException · Couldn't convert result of type java.lang.Boolean to java.lang.String`

### What is the expected behavior?
No exception

### What are the steps to reproduce the unexpected behavior?
<img width="486" alt="Screen Shot 2019-03-14 at 10 31 54 AM" src="https://user-images.githubusercontent.com/497047/54378410-7d92bd80-4644-11e9-8923-ad28e64cd04b.png">

### Do you have logging for the issue?
```
java.lang.ClassCastException: Couldn't convert result of type java.lang.Boolean to java.lang.String
        at android.net.NetworkInfo.getSubtypeName(<Xposed>:-1)
        at com.urbanairship.analytics.Event.getConnectionSubType(SourceFile:225)
        at com.urbanairship.analytics.AppForegroundEvent.getEventData(SourceFile:38)
        at com.urbanairship.analytics.Event.createEventPayload(SourceFile:117)
        at com.urbanairship.analytics.data.EventResolver.insertEvent(SourceFile:196)
        at com.urbanairship.analytics.data.EventManager.addEvent(SourceFile:130)
        at com.urbanairship.analytics.Analytics$2.run(SourceFile:185)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
```

**Comment by rafagcamargo** [comment]
The exception is slightly different for API 19: `java.lang.ClassCastException · Couldn't convert result of type boolean to int`

**Comment by rlepinski** [comment]
Odd: https://developer.android.com/reference/android/net/NetworkInfo.html#getSubtypeName()

It should be a String and not a Boolean or int. Do you have any way of reproducing this or any info around the type of devices that are causing this issue?

**Comment by rafagcamargo** [comment]
Here are the devices I'm seeing the problem:

```
API 19: Samsung Galaxy S7 active
API 23: Alcatel One Touch 5049W
API 23: ALCATEL TRU 5065N
```

I'm working to reproduce the steps.

**Comment by rlepinski** [comment]
@rafagcamargo I am going to catch the `ClassCastException` in 9.7.1 and see if we can avoid the subtype in a future release. Please continue to provide more information. It might be a bug you should file on Android bug tracker.

**Comment by BrianBatchelder** [comment]
@rafagcamargo Please let us know if you see this again. It might be a bug that should be filed on the Android bug tracker.
