### ISSUE TITLE
Amazon Device Crash

### ISSUE THREAD

**Issue by grunt2001c** [urbanairship/android-library#116]
### What Urban Airship dependencies are you using?
 api "com.urbanairship.android:urbanairship-fcm:9.1.1"
api "com.urbanairship.android:urbanairship-adm:9.1.1"

### What are the versions of any relevant development tools you are using?
9.1.1 UA library

# Report

### What unexpected behavior are you seeing?
App crashes on launch

### What is the expected behavior?
should launch and be able to push 

### What are the steps to reproduce the unexpected behavior?
Install on amazon device and launch app.

### Do you have logging for the issue?
03-20 14:47:44.722 9277-9330/com.{omited}.android E/AndroidRuntime: FATAL EXCEPTION: Thread-4518
    Process: com.{omited}.android, PID: 9277
    java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/app/NotificationManagerCompat;
        at com.urbanairship.push.PushManager.<init>(PushManager.java:316)
        at com.urbanairship.push.PushManager.<init>(PushManager.java:302)
        at com.urbanairship.UAirship.init(UAirship.java:602)
        at com.urbanairship.UAirship.executeTakeOff(UAirship.java:369)
        at com.urbanairship.UAirship.access$000(UAirship.java:49)
        at com.urbanairship.UAirship$2.run(UAirship.java:329)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.app.NotificationManagerCompat" on path: DexPathList[[zip file "/data/app/com.{omited}.android-2/base.apk", zip file "/data/app/com.{omited}.amazon.android-2/split_lib_dependencies_apk.apk", zip file "/data/app/com.{omited}.amazon.android-2/split_lib_slice_0_apk.apk", zip file "/system/priv-app/DeviceMessagingAndroidSDK/DeviceMessagingAndroidSDK.apk", zip file "/system/priv-app/MetricsApi/MetricsApi.apk", zip file "/system/priv-app/com.amazon.dp.logger/com.amazon.dp.logger.apk"],nativeLibraryDirectories=[/data/app/com.{omited}.android-2/lib/arm, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at com.urbanairship.push.PushManager.<init>(PushManager.java:316) 
        at com.urbanairship.push.PushManager.<init>(PushManager.java:302) 
        at com.urbanairship.UAirship.init(UAirship.java:602) 
        at com.urbanairship.UAirship.executeTakeOff(UAirship.java:369) 
        at com.urbanairship.UAirship.access$000(UAirship.java:49) 
        at com.urbanairship.UAirship$2.run(UAirship.java:329) 
        at java.lang.Thread.run(Thread.java:818) 
    	Suppressed: java.lang.ClassNotFoundException: android.support.v4.app.NotificationManagerCompat
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        		... 8 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

**Comment by grunt2001c** [comment]
Using Androidx and following versions
       urbanAirshipVersion = "9.1.1"
        googlePlayLocationServicesVersion = "15.0.1"
        googlePlayServicesBaseVersion = "15.0.1"
        googlePlayServicesWearVersion = "15.0.1"
        googlePlayServicesAdsVersion = "15.0.1"
        googlePlayServicesAnalyticsVersion = "15.0.2"
        googlePlayServicesLocationVersion = "15.0.1"
        googlePlayServicesGCMVersion = "15.0.1"
        firebaseConfigVersion = "15.0.2"
        firebaseCoreVersion = "15.0.2"
        firebaseIndexingVersion = "15.0.1"
        firebaseMessagingVersion = "15.0.2"
        firebasePerformanceVersion = "15.0.0"

**Comment by BrianBatchelder** [comment]
@grunt2001c : Could you send us your build.gradle file?
