### ISSUE TITLE
java.lang.IllegalStateException: Not allowed to start service Intent { act=com.urbanairship.actionservice.ACTION_RUN_ACTIONS cmp=com.nbcuni.telemundo.noticiastelemundo/com.urbanairship.actions.ActionService (has extras) }: app is in background uid UidRecord{89dc7b u0a277 TRNB idle procs:1 seq(0,0,0)}

### ISSUE THREAD

**Issue by khalidr12** [urbanairship/android-library#120]
# Please fill out this template when submitting an issue.
All lines beginning with an ℹ symbol indicate information that's important for you to provide to ensure your issue is resolved as quickly and efficiently as possible.

❗For how-to inquiries involving Urban Airship functionality or use cases, please
contact (support)[https://support.urbanairship.com/hc/en-us].

# Preliminary Info

### What Urban Airship dependencies are you using?
ℹ Please include Urban Airship dependencies and their versions here.
com.urbanairship.android:urbanairship-sdk:8.9.+
### What are the versions of any relevant development tools you are using?
ℹ If applicable, please include any relevant information about the version of your
IDE, plugin(s), or package manager(s) here.

# Report

### What unexpected behavior are you seeing?
ℹ Please provide a brief description of the unexpected behavior here.
We see to be calling the Intent when the application is in background and so it crashes. 
### What is the expected behavior?
ℹ Please provide a brief description of the expected behavior here.

### What are the steps to reproduce the unexpected behavior?
ℹ Please provide reproduction steps here.
I was not given any steps on how to reproduce the issue; I was only given a stack trace. I am just an intern here so the code base is very much unknown to me
### Do you have logging for the issue?
ℹ Please provide links to gists of any pertinent logs here.
#0. Crashed: main
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3346)
       at android.app.ActivityThread.-wrap17(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1700)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6759)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)

--

Fatal Exception: java.lang.RuntimeException: Unable to start receiver com.urbanairship.CoreReceiver: java.lang.IllegalStateException: Not allowed to start service Intent { act=com.urbanairship.actionservice.ACTION_RUN_ACTIONS cmp=com.nbcuni.telemundo.noticiastelemundo/com.urbanairship.actions.ActionService (has extras) }: app is in background uid UidRecord{89dc7b u0a277 TRNB idle procs:1 seq(0,0,0)}
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3346)
       at android.app.ActivityThread.-wrap17(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1700)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6759)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)

Caused by java.lang.IllegalStateException: Not allowed to start service Intent { act=com.urbanairship.actionservice.ACTION_RUN_ACTIONS cmp=com.nbcuni.telemundo.noticiastelemundo/com.urbanairship.actions.ActionService (has extras) }: app is in background uid UidRecord{89dc7b u0a277 TRNB idle procs:1 seq(0,0,0)}
       at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1506)
       at android.app.ContextImpl.startService(ContextImpl.java:1462)
       at android.content.ContextWrapper.startService(ContextWrapper.java:644)
       at android.content.ContextWrapper.startService(ContextWrapper.java:644)
       at com.urbanairship.actions.ActionService.runActions(ActionService.java:159)
       at com.urbanairship.CoreReceiver.onNotificationOpened(CoreReceiver.java:254)
       at com.urbanairship.CoreReceiver.onReceive(CoreReceiver.java:57)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3335)
       at android.app.ActivityThread.-wrap17(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1700)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6759)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)

**Comment by rlepinski** [comment]
This issue is fixed in 9.7.1, please update.
