### ISSUE TITLE
java.lang.NoSuchMethodError: No static method zzb

### ISSUE THREAD

**Issue by SiddarthG** [urbanairship/android-library#14]
I get this crash, no static method zzb, and after finding other similar issues i found out that this happens if google services  version is different in different places, i want to know what version of google services is used by UrbanAirship, i am using latest version of firebase 11.0.1 and google services 3.1.0

here is the crash report:

```
No static method zzb(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; in class Lcom/google/android/gms/common/internal/zzac; or its super classes (declaration of 'com.google.android.gms.common.internal.zzac' appears in /data/app/com.appsriv.insulsafe-2/split_lib_dependencies_apk.apk:classes18.dex)
                                                     at com.google.android.gms.gcm.GcmNetworkManager.zzez(Unknown Source)
                                                     at com.google.android.gms.gcm.GcmNetworkManager.zza(Unknown Source)
                                                     at com.google.android.gms.gcm.GcmNetworkManager.zzb(Unknown Source)
                                                     at com.google.android.gms.gcm.GcmNetworkManager.cancelTask(Unknown Source)
                                                     at com.urbanairship.job.GcmScheduler.cancel(GcmScheduler.java:28)
                                                     at com.urbanairship.job.JobDispatcher.cancel(JobDispatcher.java:148)
                                                     at com.urbanairship.job.JobDispatcher.dispatchHelper(JobDispatcher.java:133)
                                                     at com.urbanairship.job.JobDispatcher.dispatch(JobDispatcher.java:99)
                                                     at com.urbanairship.push.PushManager.startUpdateTagsService(PushManager.java:975)
                                                     at com.urbanairship.push.PushManager.init(PushManager.java:319)
                                                     at com.urbanairship.UAirship.init(UAirship.java:591)
                                                     at com.urbanairship.UAirship.executeTakeOff(UAirship.java:364)
                                                     at com.urbanairship.UAirship.access$000(UAirship.java:44)
                                                     at com.urbanairship.UAirship$2.run(UAirship.java:324)
                                                     at java.lang.Thread.run(Thread.java:818)
```

**Comment by SiddarthG** [comment]
I had to downgrade firebase versions to 10.2.1 because urbanAirship uses 10.2.1, this is bas as its not up to date with the firebase version, so app is guaranteed to crash if urban airship changes to 10.3.1

**Comment by rlepinski** [comment]
@SiddarthG You just need to define the gcm dependency:

```
compile 'com.google.android.gms:play-services-gcm:11.0.1'
```

And it will force UA to use the newer version.

**Comment by SiddarthG** [comment]
ok Thanks
