### ISSUE TITLE
Default FirebaseApp is not initialized in this process 

### ISSUE THREAD

**Issue by halysongoncalves** [urbanairship/android-library#146]
Hello,

We have identified crash in `Default FirebaseApp is not initialized in this process ` that has affected our users.
 

`    java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.globo.globotv. Make sure to call FirebaseApp.initializeApp(Context) first.
        at com.google.firebase.FirebaseApp.getInstance(com.google.firebase:firebase-common@@19.2.0:183)
        at com.urbanairship.push.fcm.FcmPushProvider.isAvailable(FcmPushProvider.java:90)
        at com.urbanairship.PushProviders.init(PushProviders.java:64)
        at com.urbanairship.PushProviders.load(PushProviders.java:40)
        at com.urbanairship.UAirship.init(UAirship.java:682)
        at com.urbanairship.UAirship.executeTakeOff(UAirship.java:421)
        at com.urbanairship.UAirship.access$000(UAirship.java:66)
        at com.urbanairship.UAirship$2.run(UAirship.java:380)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at com.urbanairship.util.AirshipThreadFactory$1.run(AirshipThreadFactory.java:49)
        at java.lang.Thread.run(Thread.java:919)`

**Comment by crow** [comment]
@halysongoncalves we'll look into it momentarily, thanks for reporting

**Comment by rlepinski** [comment]
@halysongoncalves Is this a crash?

**Comment by halysongoncalves** [comment]
Yes

**Comment by rlepinski** [comment]
@halysongoncalves I dont think it is - https://github.com/urbanairship/android-library/blob/master/urbanairship-fcm/src/main/java/com/urbanairship/push/fcm/FcmPushProvider.java#L101 We catch that exception.

**Comment by crow** [comment]
Closing due to inactivity
