### ISSUE TITLE
Error: Program type already present: dagger.Provides

### ISSUE THREAD

**Issue by mutkan** [urbanairship/android-library#153]
❗For how-to inquiries involving Airship functionality or use cases, please
contact (support)[https://support.airship.com/].

# Preliminary Info

### What Airship dependencies are you using?
implementation("com.urbanairship.android:urbanairship-fcm:13.1.2")
    implementation("com.google.firebase:firebase-messaging:20.2.0")

### What are the versions of any relevant development tools you are using?

Android Studio 3.6.3
 classpath 'com.android.tools.build:gradle:3.6.1'
kotlin_version = '1.3.71'
gradle-5.6.4-all.zip
# Report

### What unexpected behavior are you seeing?
I am migrating 9.7.1 to 13.1.2. When I tried to build, it gives me just this error; Error: Program type already present: dagger.Provides

### What is the expected behavior?
It should be built.

### What are the steps to reproduce the unexpected behavior?
I was just trying to migrate 9.7.1 to 13.1.2.
Remove AirshipReceiver, add AutoPilot and dependencies. That's it.

### Do you have logging for the issue?
Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete
        at com.android.tools.r8.utils.ExceptionUtils.withCompilationHandler(ExceptionUtils.java:65)
        at com.android.tools.r8.utils.ExceptionUtils.withD8CompilationHandler(ExceptionUtils.java:43)
        at com.android.tools.r8.D8.run(D8.java:90)
        at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:115)
        ... 93 more
Caused by: com.android.tools.r8.utils.AbortException: Error: Program type already present: dagger.Provides
        at com.android.tools.r8.utils.Reporter.failIfPendingErrors(Reporter.java:116)
        at com.android.tools.r8.utils.Reporter.fatalError(Reporter.java:74)
        at com.android.tools.r8.utils.ExceptionUtils.withCompilationHandler(ExceptionUtils.java:59)

**Comment by mutkan** [comment]
I tried many combination 
(airship: 10.0.2 firebase 17.0.1) builds
(airship: 11.0.4 firebase 18.0.0) builds
(airship: 12.0.0 firebase 19.0.0) builds
(airship: 12.2.4 firebase 20.0.1) builds
(airship: 13.0.0 firebase 20.0.1) gives the error

**Comment by rlepinski** [comment]
How are you forcing 20.0.1 with airship 13.0.0?
