### ISSUE TITLE
com.urbanairship.push.PushProvider$RegistrationException: FCM error FIS_AUTH_ERROR , Caused by: java.io.IOException: FIS_AUTH_ERROR

### ISSUE THREAD

**Issue by yomnaghussein** [urbanairship/android-library#158]
❗For how-to inquiries involving Airship functionality or use cases, please
contact (support)[https://support.airship.com/].

# Preliminary Info

### What Airship dependencies are you using?

implementation 'com.urbanairship.android:urbanairship-fcm:13.3.2'
implementation "com.urbanairship.android:urbanairship-message-center:13.3.2"
implementation "com.urbanairship.android:urbanairship-automation:13.3.2"
implementation "com.urbanairship.android:urbanairship-location:13.3.2"

### What are the versions of any relevant development tools you are using?

 implementation 'com.google.firebase:firebase-messaging:20.2.4'
implementation 'com.google.firebase:firebase-core:17.4.4'
implementation 'com.google.firebase:firebase-crashlytics:17.1.1'
implementation 'com.google.firebase:firebase-analytics:17.4.4'
 
 //GMS
implementation 'com.google.android.gms:play-services-location:17.0.0'
implementation 'com.google.android.gms:play-services-vision:20.1.0'
implementation 'com.google.android.gms:play-services-maps:17.0.0'

IDE: Android Studio
# Report

### What unexpected behavior are you seeing?

after upgrading to latest version of urbanairship which is mentioned above, notifications worked for sometimes and then suddenly stopped being sent and after alot of investigation, I found my testing devices opted out through contact lookup in urbanairship dashboard and going through logs i found this error. 
![image](https://user-images.githubusercontent.com/15186918/90192046-63718780-ddc2-11ea-821b-00d5e9c8f65b.png)

Knowing that if i downgrade urban version to: 
implementation 'com.urbanairship.android:urbanairship-fcm:12.1.1' everything works fine.

### What is the expected behavior?

registerationToken in fcm is correctly handled like the older version.
### What are the steps to reproduce the unexpected behavior?

upgrading urban to latest version.
### Do you have logging for the issue?

UALib: com.urbanairship.push.PushProvider$RegistrationException: FCM error FIS_AUTH_ERROR
        at com.urbanairship.push.fcm.FcmPushProvider.getRegistrationToken(FcmPushProvider.java:73)
        at com.urbanairship.push.PushManager.performPushRegistration(PushManager.java:1013)
        at com.urbanairship.push.PushManager.extendChannelRegistrationPayload(PushManager.java:320)
        at com.urbanairship.push.PushManager.access$000(PushManager.java:53)
        at com.urbanairship.push.PushManager$1.extend(PushManager.java:287)
        at com.urbanairship.channel.AirshipChannel.getNextChannelRegistrationPayload(AirshipChannel.java:515)
        at com.urbanairship.channel.AirshipChannel.onCreateChannel(AirshipChannel.java:657)
        at com.urbanairship.channel.AirshipChannel.onPerformJob(AirshipChannel.java:231)
        at com.urbanairship.job.Job$1.run(Job.java:90)
        at com.urbanairship.util.SerialExecutor$1.run(SerialExecutor.java:41)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at com.urbanairship.util.AirshipThreadFactory$1.run(AirshipThreadFactory.java:50)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.io.IOException: FIS_AUTH_ERROR
        at com.google.firebase.iid.GmsRpc.handleResponse(com.google.firebase:firebase-iid@@20.2.3:81)
        at com.google.firebase.iid.GmsRpc.lambda$extractResponseWhenComplete$0$GmsRpc(com.google.firebase:firebase-iid@@20.2.3:91)
        at com.google.firebase.iid.GmsRpc$$Lambda$0.then(Unknown Source:2)
        at com.google.android.gms.tasks.zze.run(com.google.android.gms:play-services-tasks@@17.0.2:5)
        at com.google.firebase.iid.FirebaseIidExecutors$$Lambda$0.execute(Unknown Source:0)
        at com.google.android.gms.tasks.zzc.zza(com.google.android.gms:play-services-tasks@@17.0.2:6)
        at com.google.android.gms.tasks.zzr.zza(com.google.android.gms:play-services-tasks@@17.0.2:19)
        at com.google.android.gms.tasks.zzu.zza(com.google.android.gms:play-services-tasks@@17.0.2:104)
        at com.google.android.gms.tasks.zze.run(com.google.android.gms:play-services-tasks@@17.0.2:15)
        at com.google.firebase.iid.FirebaseIidExecutors$$Lambda$0.execute(Unknown Source:0)
        at com.google.android.gms.tasks.zzc.zza(com.google.android.gms:play-services-tasks@@17.0.2:6)
        at com.google.android.gms.tasks.zzr.zza(com.google.android.gms:play-services-tasks@@17.0.2:19)
        at com.google.android.gms.tasks.zzu.zza(com.google.android.gms:play-services-tasks@@17.0.2:104)
        at com.google.android.gms.tasks.TaskCompletionSource.setResult(com.google.android.gms:play-services-tasks@@17.0.2:8)
        at com.google.firebase.iid.MessengerIpcClient$Request.finish(com.google.firebase:firebase-iid@@20.2.3:20)
        at com.google.firebase.iid.MessengerIpcClient$TwoWayRequest.handleResponseInternal(com.google.firebase:firebase-iid@@20.2.3:7)
        at com.google.firebase.iid.MessengerIpcClient$Request.handleResponse(com.google.firebase:firebase-iid@@20.2.3:29)
        at com.google.firebase.iid.MessengerIpcClient$Connection.receivedResponse(com.google.firebase:firebase-iid@@20.2.3:42)
        at com.google.firebase.iid.MessengerIpcClient$Connection$$Lambda$0.handleMessage(Unknown Source:2)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at com.google.android.gms.internal.firebase-iid.zze.dispatchMessageTraced(com.google.firebase:firebase-iid@@20.2.3:21)
        at com.google.android.gms.internal.firebase-iid.zze.dispatchMessage(com.google.firebase:firebase-iid@@20.2.3:11)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7814)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1047)

**Comment by rlepinski** [comment]
@yomnaghussein When you downgraded to Airship 12.x,  did you still use firebase messaging 20.2.4? That error is coming from firebase. I am still investigating, but found these:
https://github.com/firebase/firebase-android-sdk/issues/1776
https://stackoverflow.com/questions/60648040/android-firebase-version-upgrading

How are you initializing firebase?

**Comment by yomnaghussein** [comment]
@rlepinski when i downgrade urban to 12.x i use firebase messaging version  20.1.0  and they are working fine with each other. 
when i use latest version of firebase with urban version 12.x UALib: Push registration failed , FCM registration failed error occured  Caused by: java.io.IOException: FIS_AUTH_ERROR.

Also, I have tried to keep the firebase messaging version as it is 20.1.0 and only upgrade urban to latest 13.x but still have the same mentioned issue with screenshot attached above.

**Comment by rlepinski** [comment]
Could you run `./gradlew app:dependencies` and post the output for 20.1.0 and latest 13.x? The SDK has a dependency on `20.2.0`, so unless you are forcing 20.1.0 its still probably using 20.2.0. https://docs.gradle.org/current/dsl/org.gradle.api.artifacts.ResolutionStrategy.html

**Comment by rlepinski** [comment]
I am unable to reproduce this. It appears to be an FCM issue, so you might want to report it to firebase. Assuming you are not upgrading firebase messaging when using Airship SDK 12.x and the problem goes away, you can force that version by adding `force=true` to your dependency:

```
implementation 'com.google.firebase:firebase-messaging:20.0.1' {
  force = true
}
```

If you run the dependency task again you should see it resolve to the right version.

**Comment by yomnaghussein** [comment]
thank you for your support i will report it to firebase
