### ISSUE TITLE
Unable to stop service com.urbanairship.job.AndroidJobService

### ISSUE THREAD

**Issue by halysongoncalves** [urbanairship/android-library#159]
Hello,

We have identified crash in `Unable to stop service com.urbanairship.job.AndroidJobService` that has affected our users

`
Fatal Exception: java.lang.RuntimeException: Unable to stop service com.urbanairship.job.AndroidJobService@995012f: java.lang.RuntimeException: android.os.DeadSystemException
       at android.app.ActivityThread.handleStopService(ActivityThread.java:4351)
       at android.app.ActivityThread.access$2000(ActivityThread.java:232)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2063)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:241)
       at android.app.ActivityThread.main(ActivityThread.java:7604)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
`

![Captura de Tela 2020-08-19 às 09 43 55](https://user-images.githubusercontent.com/5872045/90636134-8eb00880-e200-11ea-9846-bf89ff00cb53.png)

![Captura de Tela 2020-08-19 às 09 44 59](https://user-images.githubusercontent.com/5872045/90636224-adae9a80-e200-11ea-9be0-a53f5ae5e1d4.png)

**Comment by BrianBatchelder** [comment]
@halysongoncalves : Some questions for you:
- What Airship dependencies are you using? What are their versions?
- Are you able to reproduce the failure?
- Have you seen the failure on any other devices?
- Have you seen the failure on any other versions of Android?

Note: As noted in [our response](https://github.com/urbanairship/android-library/issues/132#issuecomment-554433736) to a previous report, when you see `com.urbanairship.job.AndroidJobService`, that is just the reason why the app was started. It is possible that non-Airship code is causing or contributing to this issue.

**Comment by BrianBatchelder** [comment]
Let us know if you have any further information on this.
