### ISSUE TITLE
LocaleChangeListener leads to IllegaleStateException

### ISSUE THREAD

**Issue by StefMa** [urbanairship/android-library#160]
❗For how-to inquiries involving Airship functionality or use cases, please
contact (support)[https://support.airship.com/].

# Preliminary Info
In some situations I do not initialize the Airship for our App. 
Some reason could be that a user don't accept our privacy policy.

Unfortunately we receive crashes from the `LocaleChangeListener` in such cases.

### What Airship dependencies are you using?

`com.urbanairship.android:urbanairship-fcm:13.3.2`

### What are the versions of any relevant development tools you are using?

Doesn't matter, I think.

# Report

### What unexpected behavior are you seeing?

The App crashes because I guess the `LocaleChangeReceiver` assumed that Airship is initialized.
Crash report:
```
java.lang.IllegalStateException: Take off must be called before shared()
    at com.urbanairship.UAirship.shared(UAirship.java:182)
    at com.urbanairship.locale.LocaleChangeReceiver.onReceive(LocaleChangeReceiver.java:29)
    at android.app.ActivityThread.handleReceiver(ActivityThread.java:3190)
    at android.app.ActivityThread.-wrap17
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1675)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6518)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
java.lang.RuntimeException: Unable to start receiver com.urbanairship.locale.LocaleChangeReceiver: java.lang.IllegalStateException: Take off must be called before shared()
    at android.app.ActivityThread.handleReceiver(ActivityThread.java:3197)
    at android.app.ActivityThread.-wrap17
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1675)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6518)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

### What is the expected behavior?

The App does not crash if Airship is not initialized..

### What are the steps to reproduce the unexpected behavior?

I haven't tried it.
But I think the following *could* reproduce it:

* Add Airship dependency to your project
* Don't do anything more (No setup in code at all)
* Start the App
* Move the App in background
* Change the language in the user phone settings 
* 💣  Crash

### Do you have logging for the issue?

The stacktrace is all I have..

**Comment by marc-scig** [comment]
Hi @StefMa,

Thanks for letting us know. This looks like an easy one to fix, so we should have a patch available soon. I'll keep you posted.

**Comment by rlepinski** [comment]
Here is a workaround until we can get a patch out:

```
public class FixedLocaleChangeReceiver extends LocaleChangeReceiver {
    @Override
    public void onReceive(@NonNull Context context, @Nullable Intent intent) {
        if (UAirship.isFlying() || UAirship.isTakingOff()) {
            super.onReceive(context, intent);
        }
    }
}
```

Then register this in place of the airship one:

```
      <receiver android:name="com.urbanairship.locale.LocaleChangeReceiver" tools:node="remove" />

        <receiver
            android:name=".FixedLocaleChangeReceiver"
            android:exported="false">
            <intent-filter>
                <action android:name="android.intent.action.LOCALE_CHANGED" />
            </intent-filter>
        </receiver>
```

**Comment by marc-scig** [comment]
@StefMa 13.3.5 is out. This should address your issue, but let us know if you have any additional trouble.
