### ISSUE TITLE
Fatal Exception: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/urbanairship/app/GlKbalActivityMonitor$1;

### ISSUE THREAD

**Issue by hampubogdan** [urbanairship/android-library#164]
# Preliminary Info

### What Airship dependencies are you using?
    def airshipVersion = "14.0.0"
    // FCM push provider
    implementation "com.urbanairship.android:urbanairship-fcm:$airshipVersion"
    // In-App Messaging
    implementation "com.urbanairship.android:urbanairship-automation:$airshipVersion"
    // Message Center
    implementation "com.urbanairship.android:urbanairship-message-center:$airshipVersion"

### What are the versions of any relevant development tools you are using?

    implementation 'com.google.android.play:core:1.6.4'
    implementation 'com.google.android.gms:play-services-awareness:15.0.1'
    implementation 'com.google.android.gms:play-services-location:15.0.1'
    implementation 'com.google.android.gms:play-services-maps:15.0.1'
    implementation 'com.google.android.gms:play-services-analytics:16.0.8'
    implementation 'com.google.firebase:firebase-analytics:17.4.3'
    implementation 'com.google.firebase:firebase-core:17.4.3'
    implementation 'com.google.firebase:firebase-crashlytics:17.0.1'
    implementation 'com.google.firebase:firebase-messaging:20.2.0'

# Report

### What unexpected behavior are you seeing?
Production crash after migrating to version 14.0.0

### What are the steps to reproduce the unexpected behavior?
No steps available. 

Affected users: 
Android 9 - Galaxy Note8 - 100% background

```
Proguard rules used for Airship classes:
-dontnote com.urbanairship.**
-dontwarn com.urbanairship.**
-keep class com.urbanairship.** { *; }
```

### Do you have logging for the issue?
```
Fatal Exception: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/urbanairship/app/GlKbalActivityMonitor$1;
       at com.urbanairship.app.GlobalActivityMonitor.<init>(GlobalActivityMonitor.java:43)
       at com.urbanairship.app.GlobalActivityMonitor.shared(GlobalActivityMonitor.java:129)
       at com.urbanairship.UrbanAirshipProvider.onCreate(UrbanAirshipProvider.java:131)
       at android.content.ContentProvider.attachInfo(ContentProvider.java:1940)
       at android.content.ContentProvider.attachInfo(ContentProvider.java:1915)
       at android.app.ActivityThread.installProvider(ActivityThread.java:6765)
       at android.app.ActivityThread.installContentProviders(ActivityThread.java:6312)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6227)
       at android.app.ActivityThread.access$1200(ActivityThread.java:238)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1787)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7073)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
```

```
Caused by java.lang.ClassNotFoundException: Didn't find class "com.urbanairship.app.GlKbalActivityMonitor$1" on path: DexPathList[[zip file "/system/framework/com.google.android.maps.jar", zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.XXXXXX.mobile-ZZZZZZZZ==/base.apk", zip file "/data/app/com.XXXXXX.mobile-ZZZZZZZZ==/split_config.arm64_v8a.apk", zip file "/data/app/com.XXXXXX.mobile-ZZZZZZZZ==/split_config.xxhdpi.apk"],nativeLibraryDirectories=[/data/app/com.XXXXXX.mobile-ZZZZZZZZ==/lib/arm64, /data/app/com.XXXXXX.mobile-ZZZZZZZZ==/base.apk!/lib/arm64-v8a, /data/app/com.XXXXXX.mobile-ZZZZZZZZ==/split_config.arm64_v8a.apk!/lib/arm64-v8a, /data/app/com.XXXXXX.mobile-ZZZZZZZZ==/split_config.xxhdpi.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
       at com.urbanairship.app.GlobalActivityMonitor.<init>(GlobalActivityMonitor.java:43)
       at com.urbanairship.app.GlobalActivityMonitor.shared(GlobalActivityMonitor.java:129)
       at com.urbanairship.UrbanAirshipProvider.onCreate(UrbanAirshipProvider.java:131)
       at android.content.ContentProvider.attachInfo(ContentProvider.java:1940)
       at android.content.ContentProvider.attachInfo(ContentProvider.java:1915)
       at android.app.ActivityThread.installProvider(ActivityThread.java:6765)
       at android.app.ActivityThread.installContentProviders(ActivityThread.java:6312)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6227)
       at android.app.ActivityThread.access$1200(ActivityThread.java:238)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1787)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7073)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

```

**Comment by marc-scig** [comment]
Hi @hampubogdan,

That's odd, I'd expect your rule to cover this class. Are you using Proguard or R8? Also do you have any sense of how frequent this crash is?

**Comment by rlepinski** [comment]
Also `GlKbalActivityMonitor` looks like a typod `GlobalActivityMonitor`.  Could you post your mapping.txt ?

**Comment by hampubogdan** [comment]
@marc-scig @rlepinski we are using DexGuard.

> DexGuard is built on ProGuard. This makes it easy to upgrade: you can reuse your ProGuard configuration and implement DexGuard's additional layers of protection.

These are the release configurations: 

```
release {
            debuggable false
            ...
            proguardFile getDefaultDexGuardFile('FILE.pro')
            proguardFile 'FILE.txt'
            ...
}
```
`minifyEnabled` property is not enabled. This means we are using the default value for this property, which is **false**.

This issue has 4 crashes affecting 1 user.

I'll attach the mapping file via e-mail to support@airship.com.

**Comment by jaymutzafi** [comment]
The file is too big. Here is the zip of it:
[mapping.txt.zip](https://github.com/urbanairship/android-library/files/5367828/mapping.txt.zip)

**Comment by hampubogdan** [comment]
@jaymutzafi please remove your comment and any reference to the mapping file from public tracker.

**Comment by jaymutzafi** [comment]
@hampubogdan Sorry I misunderstood your email request. Removed.

**Comment by rlepinski** [comment]
@hampubogdan I honestly have no idea whats going on here. We do not have any SDK code that references `GlkbalActivityMonitor`, nor are we using reflection anywhere.  Here is the line thats failing - https://github.com/urbanairship/android-library/blob/main/urbanairship-core/src/main/java/com/urbanairship/app/GlobalActivityMonitor.java#L129. It's just the constructor for the class that it's calling.

1 of how many users?

**Comment by hampubogdan** [comment]
@rlepinski We have just released a new version last week. The percentage of adoption is in a medium range and we have like 250k users for this new version.
I know that 1 user is insignificant, but we are trying to determine the cause of the crash from the incipient phase.

We will continue to monitor this crash to see if the numbers are increasing. At this point, as @marc-scig mentioned, this class should be covered by the Proguard rules.

```
-dontnote com.urbanairship.**
-dontwarn com.urbanairship.**
-keep class com.urbanairship.** { *; }
```

**Comment by rlepinski** [comment]
@hampubogdan any updates on this? It looks like a proguard/dexguard issue, but if thats the case you would expect to see it be an issue everywhere.

**Comment by hampubogdan** [comment]
@rlepinski unfortunately, no updates. In the past few days, the adoption of our latest release build increased (the one with the Airship v14.0.0), but there weren't new occurrences of this crash. This is a good think, but will continue to monitor this crash. I think you can close this issue.
Thank you for your support!

**Comment by rlepinski** [comment]
Thanks for the update. We can reopen if it becomes a bigger issue.
