### ISSUE TITLE
SQLite crashes triggered from Airship maintenance tasks pt 2

### ISSUE THREAD

**Issue by darrentaft** [urbanairship/android-library#166]
# Preliminary Info

### What Airship dependencies are you using?

urbanairship-fcm:14.0.3
urbanairship-automation:14.0.3
urbanairship-message-center:14.0.3

### What are the versions of any relevant development tools you are using?
N/A

# Report

### What unexpected behavior are you seeing?

Crashes from Airship reported to Crashlytics

### What is the expected behavior?

Don't crash

### What are the steps to reproduce the unexpected behavior?

User had just launched the app, and the following line of code was the last thing known to be executed:

airship.channel.editAttributes().setAttribute(LAST_USED_ATTRIBUTE, sdf.format(Date())).apply()

### Do you have logging for the issue?

The following crash has been logged 647 times by a single user:

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void f.l.s0.j.j(android.database.sqlite.SQLiteDatabase)' on a null object reference
       at com.urbanairship.util.DataManager$1.onConfigure(DataManager.java:75)
       at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:462)
       at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:415)
       at com.urbanairship.util.DataManager.getReadableDatabase(DataManager.java:142)
       at com.urbanairship.util.DataManager.rawQuery(DataManager.java:334)
       at com.urbanairship.automation.storage.LegacyDataManager.querySchedules(LegacyDataManager.java:376)
       at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:449)
       at java.lang.StringBuilder.append(StringBuilder.java:137)
       at android.app.ContextImpl.makeFilename(ContextImpl.java:2825)
       at android.app.ContextImpl.getDatabasePath(ContextImpl.java:897)
       at android.content.ContextWrapper.getDatabasePath(ContextWrapper.java:337)
       at com.urbanairship.util.DataManager.databaseExists(DataManager.java:363)
       at com.urbanairship.automation.storage.LegacyDataMigrator.migrateData(LegacyDataMigrator.java:61)
       at com.urbanairship.automation.AutomationEngine$4.run(AutomationEngine.java:242)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:237)
       at android.os.HandlerThread.run(HandlerThread.java:67)
       at com.urbanairship.util.AirshipHandlerThread.run(AirshipHandlerThread.java:29)
```

Possibly linked to issue #165

**Comment by marc-scig** [comment]
Thanks @darrentaft, we'll take a look. Is it fair to assume that the impacted audience is similar this time around as well?

**Comment by darrentaft** [comment]
Absolutely @marc-scig - just a single report so far.

**Comment by rlepinski** [comment]
@darrentaft The stack trace seems wrong to me, did you modify it at all? I am not sure how `AbstractStringBuilder` is calling `querySchedules`

**Comment by darrentaft** [comment]
No modifications - just confirmed Play Store reports the same signature

**Comment by rlepinski** [comment]
I am not sure how to proceed, I don't think this stacktrace is accurate. 

Here is the only place `querySchedules` gets called:

```
private void migrateDatabase(@NonNull LegacyDataManager dataManager, @Nullable Migrator migrator) {
        Cursor cursor = null;
        try {
            cursor = dataManager.querySchedules();
            if (cursor != null) {
                migrateDataFromCursor(cursor, migrator);
            }
        } catch (Exception e) {
            Logger.error(e, "Error when migrating database.");
        } finally {
            closeCursor(cursor);
            dataManager.deleteAllSchedules();
            dataManager.close();
            dataManager.deleteDatabase(context);
        }
    }
```

It should catch any NPE. 

The `onConfigure` piece is even weirder:

```
  public DataManager(@NonNull Context context, @NonNull String appKey, @NonNull String name, int version) {
        this.path = migrateDatabase(context, appKey, name);
        ... 
        openHelper = new SQLiteOpenHelper(context, path, null, version) {
            @Override
            public void onConfigure(@NonNull SQLiteDatabase db) {
                super.onConfigure(db);
                DataManager.this.onConfigure(db);
            }
            
            ...
        };
    }
```
According to the stack trace, `DataManager.this.onConfigure(db);`. -  `this` is the null object

Is it possible the stacktrace is using the wrong proguard map? Has this user been crashing on multiple app versions?

**Comment by darrentaft** [comment]
There's no chance that the wrong map is being used - it's delivered to Play Store as part of the app bundle, and sent to Crashlytics as part of the build process.  Both locations report the same stack trace.
It has only affected 1 user (1036 times over 2 days) with just the latest app version.  I'll close this down, and reopen if we get any reports in future builds. Thanks.
