### ISSUE TITLE
java.util.UnknownFormatConversionException: Conversion = 'End of String'

### ISSUE THREAD

**Issue by Abhishek284** [urbanairship/android-library#171]
Dependencies:
implementation 'com.urbanairship.android:urbanairship-message-center:14.1.0
implementation 'com.urbanairship.android:urbanairship-automation:14.1.0'

Android studio: 4.0.1

We see intermittent crashes with the following report

`java.util.UnknownFormatConversionException: Conversion = 'End of String'
        at java.util.Formatter$FormatSpecifierParser.peek(Formatter.java:2642)
        at java.util.Formatter$FormatSpecifierParser.<init>(Formatter.java:2603)
        at java.util.Formatter.parse(Formatter.java:2558)
        at java.util.Formatter.format(Formatter.java:2505)
        at java.util.Formatter.format(Formatter.java:2459)
        at java.lang.String.format(String.java:2911)
        at com.urbanairship.LoggingCore.log(LoggingCore.java:107)
        at com.urbanairship.Logger.debug(Logger.java:159)
        at com.urbanairship.automation.InAppAutomation.resolveDeferred(InAppAutomation.java:643)
        at com.urbanairship.automation.InAppAutomation.access$1200(InAppAutomation.java:59)
        at com.urbanairship.automation.InAppAutomation$9.run(InAppAutomation.java:583)
        at com.urbanairship.util.RetryingExecutor$ChainedOperations.run(RetryingExecutor.java:209)
        at com.urbanairship.util.RetryingExecutor$2.run(RetryingExecutor.java:135)
        at com.urbanairship.util.SerialExecutor$1.run(SerialExecutor.java:41)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at com.urbanairship.util.AirshipThreadFactory$1.run(AirshipThreadFactory.java:50)
        at java.lang.Thread.run(Thread.java:919)`

I have not seen this crash in 14.0.2. This crash happens intermittently. No exact steps to reproduce.

**Comment by marc-scig** [comment]
Hi @Abhishek284,

Thanks for lettings us know. It looks like there may be a messed up string format in there, so we should be able to fix this soon.

**Comment by rlepinski** [comment]
Fixed in 14.1.3. You can also prevent this crash if you set your log level to above debug (like info, warning, error).
