### ISSUE TITLE
UrbanAirship 1.4.20 and above crashing on App setup with Dagger and DaggerWorkerFactory

### ISSUE THREAD

**Issue by sanogueralorenzo** [urbanairship/android-library#180]
# Preliminary Info

### What Airship dependencies are you using?
1.4.20 or anything above com.urbanairship.android:urbanairship-fcm

# Report

### What unexpected behavior are you seeing?
Workers from Urban Airship is crashing on app start

### What is the expected behavior?
Workers from Urban Airship should not crash on app start

### What are the steps to reproduce the unexpected behavior?
1. Have dagger in your project with DaggerWorkerFactory https://gist.github.com/lucassales2/673f95a82722238e80b09696e148679c
2. Open the app
3. App crashes

### Do you have logging for the issue?
```
java.lang.IllegalArgumentException: unknown worker class name: com.urbanairship.job.AirshipWorker
        at com.example.presentation.di.DaggerWorkerFactory.createWorker(DaggerWorkerFactory.kt:21)
        at androidx.work.WorkerFactory.createWorkerWithDefaultFallback(WorkerFactory.java:83)
        at androidx.work.impl.WorkerWrapper.runWorker(WorkerWrapper.java:244)
        at androidx.work.impl.WorkerWrapper.run(WorkerWrapper.java:136)
        at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```

For the internal workers of the app I'm working on we require to have dagger to inject the graph

Any version of urban airship 1.4.20 or above will crash the app with the above

What is the solution for the above?

**Comment by rlepinski** [comment]
From the [docs](https://developer.android.com/reference/androidx/work/WorkerFactory#createWorker(android.content.Context,%20java.lang.String,%20androidx.work.WorkerParameters)):
```
Throwing an Exception here will crash the application. If a WorkerFactory is unable to create an instance of the ListenableWorker, it should return null so it can delegate to the default WorkerFactory.
```

Instead of throwing an exception return null so it falls back to the default worker factory.
