### ISSUE TITLE
Fatal Exception: java.lang.SecurityException Package android does not belong to 10031

### ISSUE THREAD

**Issue by WalidMaata** [urbanairship/android-library#185]
# Preliminary Info

### What Airship dependencies are you using?
"com.urbanairship.android:urbanairship-fcm:14.5.0",
"com.urbanairship.android:urbanairship-automation:14.5.0

# Report

### What unexpected behavior are you seeing?
App Crash

### What are the steps to reproduce the unexpected behavior?
we can't reproduice the crash but we got the log from the crashlytics 
**All affected devices with :  Android 11**

### Do you have logging for the issue?
Fatal Exception: java.lang.SecurityException: Package android does not belong to 10246
       at android.os.Parcel.createExceptionOrNull(Parcel.java:2385)
       at android.os.Parcel.createException(Parcel.java:2369)
       at android.os.Parcel.readException(Parcel.java:2352)
       at android.os.Parcel.readException(Parcel.java:2294)
       at android.net.IConnectivityManager$Stub$Proxy.requestNetwork(IConnectivityManager.java:4597)
       at android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:4194)
       at android.net.ConnectivityManager.registerDefaultNetworkCallback(ConnectivityManager.java:4706)
       at android.net.ConnectivityManager.registerDefaultNetworkCallback(ConnectivityManager.java:4673)
       at com.urbanairship.automation.NetworkMonitor.registerNetworkCallback(NetworkMonitor.java:40)
       at com.urbanairship.automation.NetworkMonitor.setConnectionListener(NetworkMonitor.java:57)
       at com.urbanairship.automation.AutomationEngine.start(AutomationEngine.java:259)
       at com.urbanairship.automation.InAppAutomation.init(InAppAutomation.java:252)
       at com.urbanairship.UAirship.init(UAirship.java:790)
       at com.urbanairship.UAirship.executeTakeOff(UAirship.java:421)
       at com.urbanairship.UAirship.access$000(UAirship.java:64)
       at com.urbanairship.UAirship$2.run(UAirship.java:380)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.urbanairship.util.AirshipThreadFactory$1.run(AirshipThreadFactory.java:50)
       at java.lang.Thread.run(Thread.java:923)

**Comment by rlepinski** [comment]
How often is this crash occurring? Is it limited to only a few manufacturers?

**Comment by WalidMaata** [comment]
@rlepinski there is more details for the crash : 
- Devices : 97% Samsung , 1% Google , 1% Xiaomi , 1% OPPO
- Operating System : 100% Android 11
- Devices states : 100% background 
we release new version of our app 4 days ago so till now is affected approximately 100 users

**Comment by jyaganeh** [comment]
@WalidMaata Thanks for the info, and apologies for the delayed response. From what I can see in the Google Play SDK Console, this appears to be a platform issue on a small set of devices running Android 11. I don't see anything in our code that we can actually fix, but we can add a try/catch to avoid the crash as part of the next release.

**Comment by jyaganeh** [comment]
@WalidMaata This issue was fixed in the latest release (`14.6.0`). We're catching these exceptions now, so you shouldn't see any further reports after upgrading.

**Comment by WalidMaata** [comment]
thanks @jyaganeh
