### ISSUE TITLE
Fatal Exception: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/viewlift/mobile/pushnotif/AirshipListener

### ISSUE THREAD

**Issue by NG-Gaurav** [urbanairship/android-library#197]
Fatal Exception: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/viewlift/mobile/pushnotif/AirshipListener;
       at com.viewlift.mobile.pushnotif.AppCMSAutoPilot.onAirshipReady(AppCMSAutoPilot.java:28)
       at com.urbanairship.UAirship.executeTakeOff(UAirship.java:407)
       at com.urbanairship.UAirship.access$000(UAirship.java:61)
       at com.urbanairship.UAirship$2.run(UAirship.java:360)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at com.urbanairship.util.AirshipThreadFactory$1.run(AirshipThreadFactory.java:50)
       at java.lang.Thread.run(Thread.java:764)

Caused by java.lang.ClassNotFoundException: com.viewlift.mobile.pushnotif.AirshipListener
       at java.lang.VMClassLoader.findLoadedClass(VMClassLoader.java)
       at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
       at com.viewlift.mobile.pushnotif.AppCMSAutoPilot.onAirshipReady(AppCMSAutoPilot.java:28)
       at com.urbanairship.UAirship.executeTakeOff(UAirship.java:407)
       at com.urbanairship.UAirship.access$000(UAirship.java:61)
       at com.urbanairship.UAirship$2.run(UAirship.java:360)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at com.urbanairship.util.AirshipThreadFactory$1.run(AirshipThreadFactory.java:50)
       at java.lang.Thread.run(Thread.java:764)

Caused by java.lang.IllegalAccessError: Method 'void com.viewlift.mobile.pushnotif.AirshipListener.onChannelCreated(java.lang.String)' implementing interface method 'void com.urbanairship.channel.AirshipChannelListener.onChannelCreated(java.lang.String)' is not public (declaration of 'com.viewlift.mobile.pushnotif.AirshipListener' appears in /data/app/com.viewlift.hoichoi-GtQy-UTR8X5138Z-x1ybvQ==/base.apk!classes4.dex)
       at com.viewlift.mobile.pushnotif.AppCMSAutoPilot.onAirshipReady(AppCMSAutoPilot.java:28)
       at com.urbanairship.UAirship.executeTakeOff(UAirship.java:407)
       at com.urbanairship.UAirship.access$000(UAirship.java:61)
       at com.urbanairship.UAirship$2.run(UAirship.java:360)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at com.urbanairship.util.AirshipThreadFactory$1.run(AirshipThreadFactory.java:50)
       at java.lang.Thread.run(Thread.java:764)

**Comment by rlepinski** [comment]
I assume `Lcom/viewlift/mobile/pushnotif/AirshipListener` is your class? Are you using proguard or multidex? Is this happening always or a subset of devices?

**Comment by NG-Gaurav** [comment]
yes we are using both proguard and multidex. and its happening on subset of devices

**Comment by rlepinski** [comment]
@NG-Gaurav Did you get this resolved or is it still na issue?
