### ISSUE TITLE
Impossible to init the library using newest android studio version on 4x

### ISSUE THREAD

**Issue by pranav-accedo** [urbanairship/android-library#2]
Hi guys we found a bug from the last iterations using latest library 7.2.4

The library only works on lollipop devices

Here is the global gradle file we are using

buildscript {
    repositories {
        jcenter()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.1.3'
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
        classpath 'de.felixschulze.gradle:gradle-hockeyapp-plugin:3.2'

        // Google Play Services
        classpath 'com.google.gms:google-services:3.0.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
        mavenCentral()
        maven {
            url "https://jitpack.io"
        }

        maven {
            url "https://urbanairship.bintray.com/android"
        }

        flatDir { dirs "libs" }
    }
}

Also we are using support library 24 since our build tools where updated unfortunately we already tried from 24.0.0 to 24.2.0

our solution is using java 8 but that previously was not a problem

here is the stack trace the console is printing

08-24 19:58:44.640 13775-13775/accedo.teachco.tgc.android.internal E/dalvikvm: Could not find class 'com.urbanairship.AirshipConfigOptions$Builder', referenced from method com.urbanairship.UAirship.executeTakeOff
08-24 19:58:44.640 13775-13775/accedo.teachco.tgc.android.internal W/dalvikvm: VFY: unable to resolve new-instance 7892 (Lcom/urbanairship/AirshipConfigOptions$Builder;) in Lcom/urbanairship/UAirship;
08-24 19:58:44.640 13775-13775/accedo.teachco.tgc.android.internal D/dalvikvm: VFY: replacing opcode 0x22 at 0x0002
08-24 19:58:44.640 13775-13775/accedo.teachco.tgc.android.internal E/dalvikvm: Could not find class 'com.urbanairship.ApplicationMetrics', referenced from method com.urbanairship.UAirship.init
08-24 19:58:44.640 13775-13775/accedo.teachco.tgc.android.internal W/dalvikvm: VFY: unable to resolve new-instance 7898 (Lcom/urbanairship/ApplicationMetrics;) in Lcom/urbanairship/UAirship;
08-24 19:58:44.640 13775-13775/accedo.teachco.tgc.android.internal D/dalvikvm: VFY: replacing opcode 0x22 at 0x001b
08-24 19:58:44.640 13775-13775/accedo.teachco.tgc.android.internal E/dalvikvm: Could not find class 'com.urbanairship.UAirship$1', referenced from method com.urbanairship.UAirship.shared
08-24 19:58:44.640 13775-13775/accedo.teachco.tgc.android.internal W/dalvikvm: VFY: unable to resolve new-instance 7934 (Lcom/urbanairship/UAirship$1;) in Lcom/urbanairship/UAirship;
08-24 19:58:44.640 13775-13775/accedo.teachco.tgc.android.internal D/dalvikvm: VFY: replacing opcode 0x22 at 0x0000
08-24 19:58:44.640 13775-13775/accedo.teachco.tgc.android.internal E/dalvikvm: Could not find class 'com.urbanairship.UAirship$2', referenced from method com.urbanairship.UAirship.takeOff
08-24 19:58:44.650 13775-13775/accedo.teachco.tgc.android.internal W/dalvikvm: VFY: unable to resolve new-instance 7935 (Lcom/urbanairship/UAirship$2;) in Lcom/urbanairship/UAirship;
08-24 19:58:44.650 13775-13775/accedo.teachco.tgc.android.internal D/dalvikvm: VFY: replacing opcode 0x22 at 0x00a0
08-24 19:58:44.650 13775-13775/accedo.teachco.tgc.android.internal W/dalvikvm: VFY: 'this' arg 'Ljava/lang/Object;' not instance of 'Lcom/urbanairship/AirshipComponent;'
08-24 19:58:44.650 13775-13775/accedo.teachco.tgc.android.internal W/dalvikvm: VFY:  rejecting opcode 0x6e at 0x0016
08-24 19:58:44.650 13775-13775/accedo.teachco.tgc.android.internal W/dalvikvm: VFY:  rejected Lcom/urbanairship/UAirship;.tearDown ()V
08-24 19:58:44.650 13775-13775/accedo.teachco.tgc.android.internal W/dalvikvm: Verifier rejected class Lcom/urbanairship/UAirship;
08-24 19:58:44.650 13775-13775/accedo.teachco.tgc.android.internal D/AndroidRuntime: Shutting down VM
08-24 19:58:44.650 13775-13775/accedo.teachco.tgc.android.internal W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x41818da0)
08-24 19:58:44.650 13775-13775/accedo.teachco.tgc.android.internal E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                     Process: accedo.teachco.tgc.android.internal, PID: 13775
                                                                                     java.lang.VerifyError: com/urbanairship/UAirship
                                                                                         at com.urbanairship.Autopilot.automaticTakeOff(Autopilot.java:93)
                                                                                         at com.urbanairship.UrbanAirshipProvider.onCreate(UrbanAirshipProvider.java:105)
                                                                                         at android.content.ContentProvider.attachInfo(ContentProvider.java:1591)
                                                                                         at android.content.ContentProvider.attachInfo(ContentProvider.java:1562)
                                                                                         at android.app.ActivityThread.installProvider(ActivityThread.java:5279)
                                                                                         at android.app.ActivityThread.installContentProviders(ActivityThread.java:4873)
                                                                                         at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4756)
                                                                                         at android.app.ActivityThread.access$1600(ActivityThread.java:171)
                                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1369)
                                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                         at android.os.Looper.loop(Looper.java:146)
                                                                                         at android.app.ActivityThread.main(ActivityThread.java:5679)
                                                                                         at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                         at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
                                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
                                                                                         at dalvik.system.NativeStart.main(Native Method)

Also we already tried to avoid the autoairship in our manifest since we saw the error comes from Autopilot class 

<meta-data
            android:name="com.urbanairship.autopilot"
            android:value=".uairship.TeachcoAutopilot" /> 

overriding this method as this

 @Override
    public boolean allowEarlyTakeOff(@NonNull Context context) {
        return false;
    }

but this method never get hit and it always tries Autopilot class line 93 on this line

static synchronized void automaticTakeOff(@NonNull Application application, boolean earlyTakeoff) {
------->        if(!UAirship.isFlying() && !UAirship.isTakingOff()) {

Hope you can help us finding a solution for this

Our client is Teach co (We been already working with you regarding other issues)

Best

**Comment by rlepinski** [comment]
Ok, so this started happening when you started building with Java 8 and build tools 24 ? Could you post the rest of the buiild.gradle? If not, could you post if you are using jack compiler, source compatibility, target and mind sdk version, and whatever else I would need to reproduce this issue? The output of `./gradlew dependencies` might also be useful.

I dont believe it will have anything to do with autopilot, so you can leave that be. Could you also try wiping your build directory and rebuilding the app?

**Comment by aldoinfanzon** [comment]
Hi I am Aldo from Accedo we found the issue

it has to do with this library   'net.danlew:android.joda:2.9.4.1'  (Joda Time)

Also we found that the current version do not work with support library 24.2.0  (24.1.1 works fine)
Any other gradle tools works fine including the build tools

Please take this notes for future release

As a suggestion we would like that you could update firebase version 9.0.2 to newest one that brings fixes for compatibility with google play  library

Thx

**Comment by rlepinski** [comment]
@aldoinfanzon You should be able to manually specify a newer gcm module and it will be used by our SDK. What errors do you see with support library 24.2.0?

**Comment by rlepinski** [comment]
We updated our dependency versions in 7.3.0. Should be working now.
