### ISSUE TITLE
Android 8.0 request orientation crash

### ISSUE THREAD

**Issue by VanyaHuamanBottleRocket** [urbanairship/android-library#205]
# Preliminary Info

### What Airship dependencies are you using?
com.urbanairship.android:urbanairship-fcm:16.3.1
com.urbanairship.android:urbanairship-message-center:16.3.1
com.urbanairship.android:urbanairship-automation:16.3.1
com.urbanairship.android:urbanairship-location:16.3.1
com.urbanairship.android:gimbal-adapter:7.2.0

### What are the versions of any relevant development tools you are using?
Android 
Min sdk version: 24
Compile and Target sdk: 31

# Report

### What unexpected behavior are you seeing?
We are seeing an unexpected crash on Android 8.0 . Yesterday this affected 292 android 8.0 users.

### What is the expected behavior?
Not to cause crashes on 8.0. 

### What are the steps to reproduce the unexpected behavior?
Unfortunately I do not have steps to reproduce. 

### Do you have logging for the issue?

Caused by java.lang.IllegalStateException: Only fullscreen activities can request orientation
       at android.os.Parcel.readException(Parcel.java:1975)
       at android.os.Parcel.readException(Parcel.java:1913)
       at android.app.IActivityManager$Stub$Proxy.setRequestedOrientation(IActivityManager.java:6214)
       at android.app.Activity.setRequestedOrientation(Activity.java:5840)
       at com.urbanairship.android.layout.ui.ModalActivity.onCreate(ModalActivity.java:104)
       at android.app.Activity.performCreate(Activity.java:7183)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2910)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6944)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by rlepinski** [comment]
Thanks for the report. It looks like for only Android 8.0 Google tried to enforce that limitation but was removed in 8.1+. We will have a minor release soon with a fix with other scene enhancements.

**Comment by rlepinski** [comment]
Fixed in 16.4.0
