### ISSUE TITLE
Crash on ModalActivity

### ISSUE THREAD

**Issue by barry-irvine** [urbanairship/android-library#228]
❗For how-to inquiries involving Airship functionality or use cases, please
contact (support)[https://support.airship.com/].

# Preliminary Info

### What Airship dependencies are you using?

Version 17.0.1
urbanairship-core,  urbanairship-fcm, urbanairship-automation, urbanairship-message-center

### What are the versions of any relevant development tools you are using?

Android Studio Flamingo Patch 2

# Report

### What unexpected behavior are you seeing?

Crashes on Crashlytics on Pixel 3a running Android 12. (Crashlytics says 4 different users but I suspect it's the same user trying repeated installs). 

### What is the expected behavior?

No crashes

### What are the steps to reproduce the unexpected behavior?

Unknown

### Do you have logging for the issue?

Fatal Exception: java.lang.RuntimeException: Unable to destroy activity {com.gocitypass/com.urbanairship.android.layout.ui.ModalActivity}: pj.v: lateinit property loader has not been initialized
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5386)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5419)
       at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:47)
       at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7838)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003

**Comment by jyaganeh** [comment]
Hi @barry-irvine, thanks for the report. I'll look into this and am guessing we'll need to get a patch out. Will let you know when I have more info.

**Comment by jyaganeh** [comment]
@barry-irvine We just pushed [Release 17.0.3](https://github.com/urbanairship/android-library/releases/tag/17.0.3), which includes a fix for this issue. I'm going to close this for now, but please feel free to reopen if you run into any issues, and thanks again for the report. 👍
