### ISSUE TITLE
LiveUpdateDao crash 

### ISSUE THREAD

**Issue by mformetal** [urbanairship/android-library#245]
# Preliminary Info

### What Airship dependencies are you using?

com.urbanairship.android:urbanairship-fcm:17.8.1
com.urbanairship.android:urbanairship-live-update:17.8.1

### What are the versions of any relevant development tools you are using?

N/A

# Report

### What unexpected behavior are you seeing?

From our error reporting system, we're getting a crash seemingly on startup due to the `LiveUpdateDao` class. This crash occurs only on Xiaomi devices on Android 11 while our app is backgrounded. It doesn't seem to be consistent, as we've gotten a spike for about a ~month then it died down, so this may have just been a few users stuck in a crash loop, but wanted to report this in case it's something that bears investigation. 

Stacktrace:

```
  Fatal Exception: android.database.sqlite.SQLiteCantOpenDatabaseException: unable to open database file (code 14 SQLITE_CANTOPEN): , while compiling: PRAGMA journal_mode
       at android.database.sqlite.SQLiteConnection.nativePrepareStatement(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1045)
       at android.database.sqlite.SQLiteConnection.executeForString(SQLiteConnection.java:788)
       at android.database.sqlite.SQLiteConnection.setJournalMode(SQLiteConnection.java:405)
       at android.database.sqlite.SQLiteConnection.setWalModeFromConfiguration(SQLiteConnection.java:335)
       at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:258)
       at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:205)
       at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:505)
       at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:206)
       at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:198)
       at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:918)
       at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:898)
       at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:762)
       at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:751)
       at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:373)
       at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:316)
       at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableOrReadableDatabase(FrameworkSQLiteOpenHelper.kt:232)
       at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.innerGetDatabase(FrameworkSQLiteOpenHelper.kt:190)
       at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getSupportDatabase(FrameworkSQLiteOpenHelper.kt:151)
       at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.kt:104)
       at androidx.room.RoomDatabase.internalBeginTransaction(RoomDatabase.kt:528)
       at androidx.room.RoomDatabase.beginTransaction(RoomDatabase.kt:517)
       at com.urbanairship.liveupdate.data.LiveUpdateDao_Impl$18.call(LiveUpdateDao_Impl.java:547)
       at com.urbanairship.liveupdate.data.LiveUpdateDao_Impl$18.call(LiveUpdateDao_Impl.java:544)
       at androidx.room.CoroutinesRoom$Companion$execute$4$job$1.invokeSuspend(CoroutinesRoom.kt:88)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
       at androidx.room.TransactionExecutor.execute$lambda$1$lambda$0(TransactionExecutor.java:36)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)
```

### What is the expected behavior?

No crash!

### What are the steps to reproduce the unexpected behavior?

From our reporting, this seems to happen very early on in the application lifecycle.

### Do you have logging for the issue?

Nothing that seems useful unfortunately, but happy to provide as much information as requested!

**Comment by jyaganeh** [comment]
Hi @mformetal, thanks for the report! This looks fairly similar to a pair of issues on the Google IssueTracker:

* https://issuetracker.google.com/issues/239122373
* https://issuetracker.google.com/issues/152202040

Those two are related to WorkManager, but the underlying SQLite exception seems similar, and WorkManager similarly initializes its DB early on in the App lifecycle. I've also seen similar reports from other customers once or twice in the past, for a different DB.

Based on the threads above and what we've seen before, these issues seem to pop up most commonly when the device storage is full (or possibly if the filesystem is corrupted, but I'd expect to see `SQLiteDatabaseCorruptException` instead, if that were the case). 

I'm not sure if there will be a "silver bullet" fix that we can make on our side, but we'll take a look to see if there's anything we can do to attempt to recover and retry opening the DB, or if we can at least harden against crashes like this one.

A few questions for you:

* Does you app use multiple processes by any chance? If it does, WorkManager requires a "default" process to be designated and could cause issues like this if that's not being set properly.
* Do you use WorkManager or Room directly in your app? If so, what versions are you on?
* Are you able to update to a more recent SDK version (18.4.2 is the latest)? We've bumped both WorkManager and Room since SDK 17.8.1, so there's a chance that upgrading may help with this issue (between SDK 17.8.1 and SDK 18.4.2, we went from WorkManager `2.8.0` -> `2.9.0` and Room `2.5.1` -> `2.6.1`, )
* Is there anything else that might be "interesting" or less typical about your app? Wondering about things like using direct boot, programmatically clearing the app's data, etc.

**Comment by mformetal** [comment]
> Hi @mformetal, thanks for the report! This looks fairly similar to a pair of issues on the Google IssueTracker:
> 
>     * https://issuetracker.google.com/issues/239122373
> 
>     * https://issuetracker.google.com/issues/152202040
> 
> 
> Those two are related to WorkManager, but the underlying SQLite exception seems similar, and WorkManager similarly initializes its DB early on in the App lifecycle. I've also seen similar reports from other customers once or twice in the past, for a different DB.
> 
> Based on the threads above and what we've seen before, these issues seem to pop up most commonly when the device storage is full (or possibly if the filesystem is corrupted, but I'd expect to see `SQLiteDatabaseCorruptException` instead, if that were the case).
> 
> I'm not sure if there will be a "silver bullet" fix that we can make on our side, but we'll take a look to see if there's anything we can do to attempt to recover and retry opening the DB, or if we can at least harden against crashes like this one.
> 
> A few questions for you:
> 
>     * Does you app use multiple processes by any chance? If it does, WorkManager requires a "default" process to be designated and could cause issues like this if that's not being set properly.
> 
>     * Do you use WorkManager or Room directly in your app? If so, what versions are you on?
> 
>     * Are you able to update to a more recent SDK version (18.4.2 is the latest)? We've bumped both WorkManager and Room since SDK 17.8.1, so there's a chance that upgrading may help with this issue (between SDK 17.8.1 and SDK 18.4.2, we went from WorkManager `2.8.0` -> `2.9.0` and Room `2.5.1` -> `2.6.1`, )
> 
>     * Is there anything else that might be "interesting" or less typical about your app? Wondering about things like using direct boot, programmatically clearing the app's data, etc.

Thanks for your very detailed reply! A member of the team with more context will be answering these questions for you 💪

**Comment by jyaganeh** [comment]
@mformetal we pushed `v18.5.0` last week, with a small change to retry several times if the Live Update database fails to open, with a fallback to recreating the DB if it isn't openable after those attempts.

**Comment by mformetal** [comment]
> @mformetal we pushed `v18.5.0` last week, with a small change to retry several times if the Live Update database fails to open, with a fallback to recreating the DB if it isn't openable after those attempts.

We love to see it - I'll test this new version out in just a moment. Thanks for the speedy responses @jyaganeh !
