### ISSUE TITLE
Unsupportive to Android Instant App

### ISSUE THREAD

**Issue by santoshchauhan12** [urbanairship/android-library#36]
Hi Team,
I am using urbanairship from long back , but suddenly i got into the problem when i converted my existing application into Android InstantApp feature.After searching i got to know that android instant app is restricted to content providers and push notification as given in official website of android [https://developer.android.com/topic/instant-apps/prepare.html]

Is there any work around  for supporting urbanairship with Android InstantApp feature.

Below is the crash log i got when i launch my Instant App Application:-
`E/ActivityThread: Failed to find provider info for com.mypackagegame.urbanairship.provider
11-08 12:18:25.082 20430-20492/? E/xyz - UALib: Failed to insert in UrbanAirshipProvider.
                                                     java.lang.IllegalArgumentException: Unknown URL content://com.mypackagegame.urbanairship.provider/preferences
                                                         at android.content.ContentResolver.insert(ContentResolver.java:1243)
                                                         at com.urbanairship.UrbanAirshipResolver.insert(UrbanAirshipResolver.java:54)
                                                         at com.urbanairship.PreferenceDataStore$Preference.writeValue(PreferenceDataStore.java:468)
                                                         at com.urbanairship.PreferenceDataStore$Preference.access$200(PreferenceDataStore.java:348)
                                                         at com.urbanairship.PreferenceDataStore$Preference$2.run(PreferenceDataStore.java:400)
                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                         at java.lang.Thread.run(Thread.java:818)`

**Comment by rlepinski** [comment]
We are currently not compatible with Instant Apps. You will need to exclude UA in the instant app flavor but keep it in the main application. What features are you looking for us to support in the instant app?

**Comment by Santosh-Chauhan** [comment]
missed your replied....
I am looking for push notification.Is it possible to make support for UA push notification in android instant app.Currently i believe it is not available.

**Comment by rlepinski** [comment]
@Santosh-Chauhan unfortunately FCM is completely disabled so push notifications are not possible.

**Comment by Santosh-Chauhan** [comment]
Is it possible to give support FCM for Android  Instant apps  in future??

**Comment by Santosh-Chauhan** [comment]
thanks @rlepinski

**Comment by rlepinski** [comment]
Closing for now. If we have any updates on the situation we will let you know.

**Comment by scottybe** [comment]
Hi @rlepinski, I know this is really old, but is it still not possible to send push notifications to Instant Apps?

**Comment by rlepinski** [comment]
@scottybe I am having hard time finding info on it. They had a beta for notifications - https://www.youtube.com/watch?v=tXqat1JOmS8&feature=youtu.be&t=743 but I cant find any updates on that. 

From https://developer.android.com/topic/google-play-instant/getting-started/instant-enabled-app-bundle:

> In addition, instant-enabled app bundles cannot do the following:
> 
> Use background services.
> Send notifications when running in the background.
