### ISSUE TITLE
App is  crashing if compileSdkVersion is less  than 24

### ISSUE THREAD

**Issue by MacSimmy** [urbanairship/android-library#4]
My app have compiledSdkVersion 23, so while using your latest lib v8.0.2 which uses v4:support lib version 24, which is crashing the app at runtime with  following exception:

```
 FATAL EXCEPTION: main
11-15 15:37:32.858: E/AndroidRuntime(19446): Process: com..mcommerce.opal, PID: 19446
11-15 15:37:32.858: E/AndroidRuntime(19446): android.view.InflateException: Binary XML file line #14: Binary XML file line #14: Error inflating class android.support.design.widget.CollapsingToolbarLayout
11-15 15:37:32.858: E/AndroidRuntime(19446): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
11-15 15:37:32.858: E/AndroidRuntime(19446): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
11-15 15:37:32.858: E/AndroidRuntime(19446): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
11-15 15:37:32.858: E/AndroidRuntime(19446): 	at com..mcommerce.opal.framework.view.fragment.BaseFragment.onCreateView(BaseFragment.java:41)
11-15 15:37:32.858: E/AndroidRuntime(19446): 	at android.app.Fragment.performCreateView(Fragment.java:2220)
11-15 15:37:32.858: E/AndroidRuntime(19446): 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:973)
11-15 15:37:32.858: E/AndroidRuntime(19446): 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1148)
11-15 15:37:32.858: E/AndroidRuntime(19446): 	at android.app.BackStackRecord.run(BackStackRecord.java:793)
11-15 15:37:32.858: E/AndroidRuntime(19446): 	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1535)
11-15 15:37:32.858: E/AndroidRuntime(19446): 	at android.app.FragmentManagerImpl$1.run(FragmentManager.java:482)
11-15 15:37:32.858: E/AndroidRuntime(19446): 	at android.os.Handler.handleCallback(Handler.java:739)
11-15 15:37:32.858: E/AndroidRuntime(19446): 	at android.os.Handler.dispatchMessage(Handler.java:95)
11-15 15:37:32.858: E/AndroidRuntime(19446): 	at android.os.Looper.loop(Looper.java:148)
11-15 15:37:32.858: E/AndroidRuntime(19446): 	at android.app.ActivityThread.main(ActivityThread.java:5417)
11-15 15:37:32.858: E/AndroidRuntime(19446): 	at java.lang.reflect.Method.invoke(Native Method)
11-15 15:37:32.858: E/AndroidRuntime(19446): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
11-15 15:37:32.858: E/AndroidRuntime(19446): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
11-15 15:37:32.858: E/AndroidRuntime(19446): Caused by: android.view.InflateException: Binary XML file line #14: Error inflating class android.support.design.widget.CollapsingToolbarLayout
11-15 15:37:32.858: E/AndroidRuntime(19446): 	at android.view.LayoutInflater.createView(LayoutInflater.java:645)
11-15 15:37:32.858: E/AndroidRuntime(19446): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
11-15 15:37:32.858: E/AndroidRuntime(19446): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
11-15 15:37:32.858: E/AndroidRuntime(19446): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
11-15 15:37:32.858: E/AndroidRuntime(19446): 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
11-15 15:37:32.858: E/AndroidRuntime(19446): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:838)
11-15 15:37:32.858: E/AndroidRuntime(19446): 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
11-15 15:37:32.858: E/AndroidRuntime(19446): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
11-15 15:37:32.858: E/AndroidRuntime(19446): 	... 16 more
11-15 15:37:32.858: E/AndroidRuntime(19446): Caused by: java.lang.reflect.InvocationTargetException
11-15 15:37:32.858: E/AndroidRuntime(19446): 	at java.lang.reflect.Constructor.newInstance(Native Method)
11-15 15:37:32.858: E/AndroidRuntime(19446): 	at android.view.LayoutInflater.createView(LayoutInflater.java:619)
11-15 15:37:32.858: E/AndroidRuntime(19446): 	... 23 more
11-15 15:37:32.858: E/AndroidRuntime(19446): Caused by: java.lang.NoSuchMethodError: No static method setLayoutDirection(Landroid/graphics/drawable/Drawable;I)V in class Landroid/support/v4/graphics/drawable/DrawableCompat; or its super classes (declaration of 'android.support.v4.graphics.drawable.DrawableCompat' appears in /data/app/com..mcommerce.opal-1/base.apk)
11-15 15:37:32.858: E/AndroidRuntime(19446): 	at android.support.design.widget.CollapsingToolbarLayout.setStatusBarScrim(CollapsingToolbarLayout.java:663)
11-15 15:37:32.858: E/AndroidRuntime(19446): 	at android.support.design.widget.CollapsingToolbarLayout.<init>(CollapsingToolbarLayout.java:197)
11-15 15:37:32.858: E/AndroidRuntime(19446): 	at android.support.design.widget.CollapsingToolbarLayout.<init>(CollapsingToolbarLayout.java:132)
```
This is due to lib version conflicts. Can we solve this problem without forcing third client app to upgrade compiledSdkVersion to 24?

**Comment by rlepinski** [comment]
@MacSimmy We actually have code that depends on API 24, so you must build against that version. Whats stopping you from updating the compileSdkVersion?

**Comment by MacSimmy** [comment]
@rlepinski I can update compileSdkVersion to 24 without any problem. But then you should **Bold the must have requirement of API level 24 dependency** in your documentations for users. App build process  is fine even for API level 23, but crashing at runtime. That is the real problem. In my  case it was  crashing in particular screens where I have used CollapsingToolbarLayout of support.design package. So this can cause problem as there might be chances that issue is missed from developers.

**Comment by rlepinski** [comment]
@MacSimmy Thanks for the feed back.

Did Android Studio give you a warning? My AS usually tells me that I need to update my compile SDK if I am using a support library that depends on a higher version.

In general you should always use the latest SDK version to compile against. The target API will still make your app function in compatibility mode for whatever SDK version you pick.
