### ISSUE TITLE
Application Crashing on AdmPushReceiver

### ISSUE THREAD

**Issue by alokdesai-cuelogic** [urbanairship/android-library#47]
My Application is live and I am getting crash reports on AdmPushReceiver, following is the log.

Fatal Exception: java.lang.RuntimeException: Unable to start receiver com.urbanairship.push.AdmPushReceiver: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.BaseBundle.containsKey(java.lang.String)' on a null object reference
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:2586)
       at android.app.ActivityThread.access$1700(ActivityThread.java:144)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1355)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5221)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.BaseBundle.containsKey(java.lang.String)' on a null object reference
       at com.urbanairship.push.AdmPushReceiver.onReceive(Unknown Source)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:2579)
       at android.app.ActivityThread.access$1700(ActivityThread.java:144)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1355)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5221)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by rlepinski** [comment]
What SDK version are you using?

**Comment by alokdesai-cuelogic** [comment]
com.urbanairship.android:urbanairship-sdk:8.6.+ this is the sdk version I am using

**Comment by rlepinski** [comment]
Fixed in a newer version. Please update to 8.9.6
