### ISSUE TITLE
Scheduled job to change namedUser crashes after land()

### ISSUE THREAD

**Issue by valeriyo** [urbanairship/android-library#54]
When user signs out, we call `airship.namedUser.id = null` and then, shortly, `UAirship.land()`.. With some non-zero probability this results in a crash:

```
Fatal Exception: java.lang.IllegalStateException: TakeOff must be called first.
       at com.urbanairship.UAirship.getApplicationContext(UAirship.java:523)
       at com.urbanairship.UAirship.getPackageName(UAirship.java:434)
       at com.urbanairship.push.gcm.GcmPushProvider.getRegistrationToken(GcmPushProvider.java:49)
       at com.urbanairship.push.PushManagerJobHandler.onUpdatePushRegistration(PushManagerJobHandler.java:178)
       at com.urbanairship.push.PushManagerJobHandler.performJob(PushManagerJobHandler.java:118)
       at com.urbanairship.push.PushManager.onPerformJob(PushManager.java:386)
       at com.urbanairship.job.Job$1.run(Job.java:83)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
```

It looks like the scheduled job is allowed to run after `UAirship.land()` is called, which is wrong on so many levels.

**Comment by rlepinski** [comment]
Calling land is not supported, it should only be used for test code. We will make it hidden in the next release. You should never need to call it in a production app.

**Comment by valeriyo** [comment]
thanks @rlepinski for clarifying - the docs https://docs.urbanairship.com/reference/libraries/android/latest/reference/com/urbanairship/UAirship.html#land() were not clear on this method being only for internal/test use.
