### ISSUE TITLE
Crash on version 9.0.2 during app start 

### ISSUE THREAD

**Issue by rslama** [urbanairship/android-library#64]
In latest version of UA our users  facing app crash. Log:

Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.Handler.post(java.lang.Runnable)' on a null object reference
       at com.urbanairship.automation.AutomationEngine.onScheduleConditionsChanged(AutomationEngine.java:868)
       at com.urbanairship.automation.AutomationEngine.checkPendingSchedules(AutomationEngine.java:510)
       at com.urbanairship.iam.InAppMessageManager$4.onActivityResumed(InAppMessageManager.java:311)
       at com.urbanairship.ActivityMonitor$1.onActivityResumed(ActivityMonitor.java:70)
       at android.app.Application.dispatchActivityResumed(Application.java:240)
       at android.app.Activity.onResume(Activity.java:1331)
       at android.support.v4.app.FragmentActivity.onResume(FragmentActivity.java:458)
       at com.xxx.news.ui.activity.BaseActivity.onResume(BaseActivity.java:57)
       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1277)
       at android.app.Activity.performResume(Activity.java:7088)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3768)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3832)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2994)
       at android.app.ActivityThread.-wrap14(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1631)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6682)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

**Comment by rlepinski** [comment]
Thanks for the report. We will have a fix out in the next day or so.

**Comment by rlepinski** [comment]
Fixed in 9.0.4
