### ISSUE TITLE
UA v9.0.1 NullPointerException crash

### ISSUE THREAD

**Issue by noriel-divino** [urbanairship/android-library#66]
Hi UA Team, 

We have integrated the ua library in our app and as we released new build in google play store, most of our users has been experiencing this crash on the same class and same line. Any thoughts about this? 

Also, as I checked the line of code here:

> private void onScheduleConditionsChanged() {
        backgroundHandler.post(new Runnable() {
            @Override
            public void run() {
                List<ScheduleEntry> scheduleEntries = dataManager.getScheduleEntries(ScheduleEntry.STATE_PENDING_EXECUTION);
                if (scheduleEntries.isEmpty()) {
                    return;
                }
                handleTriggeredSchedules(scheduleEntries);
            }
        });
    }

Maybe the scheduleEntries has null values & try checking if it is null first ? or the dataManager ? Its just my opinion, or this is fixed with the latest ua version 9.0.4 ? any help will do & hope to hear from you soon. Thanks!

`Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.Handler.post(java.lang.Runnable)' on a null object reference
       at com.urbanairship.automation.AutomationEngine.onScheduleConditionsChanged(AutomationEngine.java:868)
       at com.urbanairship.automation.AutomationEngine.checkPendingSchedules(AutomationEngine.java:510)
       at com.urbanairship.iam.InAppMessageManager$4.onActivityResumed(InAppMessageManager.java:311)
       at com.urbanairship.ActivityMonitor$1.onActivityResumed(ActivityMonitor.java:70)
       at android.app.Application.dispatchActivityResumed(Application.java:216)
       at android.app.Activity.onResume(Activity.java:1312)
       at android.support.v4.app.FragmentActivity.onResume(FragmentActivity.java:458)
       at com.beattheq.android.mvp.views.ui.activities.BaseActivity.onResume(BaseActivity.java:33)
       at com.beattheq.android.mvp.views.ui.activities.LaunchActivity.onResume(LaunchActivity.java:71)
       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1354)
       at android.app.Activity.performResume(Activity.java:7079)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3620)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3685)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2898)
       at android.app.ActivityThread.-wrap11(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6541)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)`

**Comment by rlepinski** [comment]
This has been fixed in 9.0.4.
