### ISSUE TITLE
IllegalStateException when starting ActionService on Android 8

### ISSUE THREAD

**Issue by asos-savvasdalkitsis** [urbanairship/android-library#67]
We've seen a fee of these in our crash reports. It only happens for Android 8 devices. It does NOT seem limited to a specific vendor (like Samsung for instance). We have a good spread of devices this occurs on

```
Caused by java.lang.IllegalStateException: Not allowed to start service Intent { act=com.urbanairship.actionservice.ACTION_RUN_ACTIONS cmp=com.app/com.urbanairship.actions.ActionService (has extras) }: app is in background uid UidRecord{80bb6f2 u0a158 RCVR idle procs:1 seq(0,0,0)}
       at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1701)
       at android.app.ContextImpl.startService(ContextImpl.java:1657)
       at android.content.ContextWrapper.startService(ContextWrapper.java:644)
       at android.content.ContextWrapper.startService(ContextWrapper.java:644)
       at com.urbanairship.actions.ActionService.a(ActionService.java:159)
       at com.urbanairship.CoreReceiver.d(CoreReceiver.java:251)
       at com.urbanairship.CoreReceiver.onReceive(CoreReceiver.java:54)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3661)
       at android.app.ActivityThread.-wrap18(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1968)
       at android.os.Handler.dispatchMessage(Handler.java:108)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:7358)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:926)
```

Is this a known issue? We are using version 9.0.0 of the SDK

**Comment by rlepinski** [comment]
Its already fixed. Please update to 9.0.4
