### ISSUE TITLE
Caused by java.lang.IllegalStateException: Take off must be called before shared()

### ISSUE THREAD

**Issue by ghimire-bharat** [urbanairship/android-library#90]
# Please fill out this template when submitting an issue.
All lines beginning with an ℹ symbol indicate information that's important for you to provide to ensure your issue is resolved as quickly and efficiently as possible.

❗For how-to inquiries involving Urban Airship functionality or use cases, please
contact (support)[https://support.urbanairship.com/hc/en-us].

What Urban Airship dependencies are you using?
com.urbanairship.android:urbanairship-fcm:8.9.6
ℹ Please include Urban Airship dependencies and their versions here.

What unexpected behavior are you seeing?
you get this crash Caused by java.lang.IllegalStateException: Take off must be called before shared()
       at com.urbanairship.UAirship.shared(SourceFile:142)

Log link

Caused by java.lang.IllegalStateException: Take off must be called before shared()
       at com.urbanairship.UAirship.shared(SourceFile:142)
       at pl.tablica2.push.urbanairship.UAPush.tagCountry(SourceFile:76)
       at pl.tablica2.push.urbanairship.UAPush.tagCountry(SourceFile:69)
       at pl.tablica2.config.AppConfig.setCountry(SourceFile:121)
       at pl.tablica2.application.TablicaApplication.init(SourceFile:143)
       at pl.tablica2.application.TablicaApplication.onCreate(SourceFile:135)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1009)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4632)
       at android.app.ActivityThread.access$1800(ActivityThread.java:141)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1298)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5336)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:873)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:689)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by marc-scig** [comment]
Hi there,

This is not a bug. As the exception message says, you must call takeOff before calling shared.

https://docs.urbanairship.com/platform/android/#takeoff
