### ISSUE TITLE
Getting crash : java.lang.NullPointerException:Attempt to invoke virtual method 'java.lang.Object java.lang.ref.WeakReference.get()' on a null object reference

### ISSUE THREAD

**Issue by gaurav-mishra8** [urbanairship/android-library#94]
# Preliminary Info

### What Urban Airship dependencies are you using?
ℹ com.urbanairship.android:urbanairship-sdk:9.4.2

# Report

### What unexpected behavior are you seeing?
ℹ App is crashing as reference is null

### What is the expected behavior?
ℹApp should not crash

### What are the steps to reproduce the unexpected behavior?
ℹ Can't reproduce

### Do you have logging for the issue?
ℹ Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.ref.WeakReference.get()' on a null object reference
       at com.urbanairship.iam.InAppMessageManager.continueOnNextActivity(SourceFile:625)
       at com.urbanairship.iam.DisplayHandler.continueOnNextActivity(SourceFile:82)
       at com.urbanairship.iam.banner.BannerFragment.onStop(SourceFile:247)
       at android.app.Fragment.performStop(Fragment.java:2542)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1048)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1171)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1153)
       at android.app.FragmentManagerImpl.dispatchStop(FragmentManager.java:2061)
       at android.app.FragmentController.dispatchStop(FragmentController.java:221)
       at android.app.Activity.performStop(Activity.java:7201)
       at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4291)
       at android.app.ActivityThread.handleStopActivity(ActivityThread.java:4343)
       at android.app.ActivityThread.-wrap28(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1676)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6776)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1518)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)

**Comment by BrianBatchelder** [comment]
@gaurav-mishra8: Thanks for the report. We will look into it.

**Comment by BrianBatchelder** [comment]
@gaurav-mishra8 : Do you have any other logs for this issue?

**Comment by BrianBatchelder** [comment]
@gaurav-mishra8 : Another question. How many crashes have you seen? Please DM me with the information, if you wish.

**Comment by gaurav-mishra8** [comment]
@BrianBatchelder It seems to be happening while attempting to stop one of our activity
Below are the complete logs : 
Fatal Exception: java.lang.RuntimeException: Unable to stop activity {packageName/activityName}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.ref.WeakReference.get()' on a null object reference
       at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4783)
       at android.app.ActivityThread.handleStopActivity(ActivityThread.java:4847)
       at android.app.ActivityThread.-wrap29(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1850)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:7325)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.ref.WeakReference.get()' on a null object reference
       at com.urbanairship.iam.InAppMessageManager.continueOnNextActivity(SourceFile:625)
       at com.urbanairship.iam.DisplayHandler.continueOnNextActivity(SourceFile:82)
       at com.urbanairship.iam.banner.BannerFragment.onStop(SourceFile:247)
       at android.app.Fragment.performStop(Fragment.java:2502)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1041)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1164)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1146)
       at android.app.FragmentManagerImpl.dispatchStop(FragmentManager.java:1993)
       at android.app.FragmentController.dispatchStop(FragmentController.java:197)
       at android.app.Activity.performStop(Activity.java:7090)
       at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4780)
       at android.app.ActivityThread.handleStopActivity(ActivityThread.java:4847)
       at android.app.ActivityThread.-wrap29(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1850)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:7325)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

The amount of crashes are big around 55K in last 7 days for one of our version.Are we doing something wrong?

**Comment by BrianBatchelder** [comment]
@gaurav-mishra8 : This issue is fixed in SDK version 9.5.1 .
