### ISSUE TITLE
 Not allowed to start service Intent

### ISSUE THREAD

**Issue by sacclynrey** [urbanairship/android-library#98]
App crashed upon receiving push notification while app is closed/background
Version: 
compile('com.urbanairship.android:urbanairship-sdk:8.0.3')

11-06 15:29:15.096 1284-1349/? E/AndroidRuntime: FATAL EXCEPTION: Thread-5
    Process: ph.com.sulit.app, PID: 1284
    java.lang.IllegalStateException: Not allowed to start service Intent { act=com.urbanairship.richpush.USER_UPDATE cmp=ph.com.sulit.app/com.urbanairship.AirshipService (has extras) }: app is in background uid UidRecord{bd86afe u0a518 RCVR idle change:idle|uncached procs:1 seq(0,0,0)}
        at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1521)
        at android.app.ContextImpl.startService(ContextImpl.java:1477)
        at android.content.ContextWrapper.startService(ContextWrapper.java:650)
        at com.urbanairship.job.JobDispatcher.dispatch(JobDispatcher.java:63)
        at com.urbanairship.richpush.RichPushUser.update(RichPushUser.java:114)
        at com.urbanairship.richpush.RichPushInbox.init(RichPushInbox.java:164)
        at com.urbanairship.UAirship.init(UAirship.java:558)
        at com.urbanairship.UAirship.executeTakeOff(UAirship.java:344)
        at com.urbanairship.UAirship.access$000(UAirship.java:42)
        at com.urbanairship.UAirship$2.run(UAirship.java:304)
        at java.lang.Thread.run(Thread.java:764)

**Comment by rlepinski** [comment]
You are running a really old version of the SDK. Please update to `9.5.4` if you can, if not you should update to `8.9.7`

**Comment by sacclynrey** [comment]
Thanks @rlepinski
